### ISSUE TITLE
Docs: spring ai alibaba get started params type is error

### ISSUE THREAD

**Issue by yuluo-yx** [alibaba/spring-ai-alibaba#13]
![image](https://github.com/user-attachments/assets/1a6a5dfe-31c2-46e1-88be-af48b1988a92)

![image](https://github.com/user-attachments/assets/269ef575-93e9-4ff4-b2ab-5e75308bad8b)

![image](https://github.com/user-attachments/assets/c013843a-2db5-4952-b3c1-9f05afc88157)

I will update docs

**Comment by chickenlj** [comment]
Please go ahead.

**Comment by yuluo-yx** [comment]
https://github.com/spring-cloud-alibaba-group/spring-cloud-alibaba-group.github.io/pull/272 

ptal @chickenlj

**Comment by chickenlj** [comment]
Merged
