### ISSUE TITLE
【WIP FC】No function callback found for function name

### ISSUE THREAD

**Issue by PolarishT** [alibaba/spring-ai-alibaba#198]
我们鼓励使用英文，如果不能直接使用，可以使用翻译软件，您仍旧可以保留中文原文。另外请按照如下要求提交相关信息节省社区维护同学的理解成本，否则该讨论极有可能直接被忽视或关闭。
We recommend using English. If you are non-native English speaker, you can use the translation software. In addition, please submit relevant information according to the following requirements to save the understanding cost of community maintenances, otherwise the discussion is very likely to be ignored or closed directly.

**Which Component**

Spring AI Alibaba Plugin

**Is your feature request related to a problem? Please describe.**

when we use Spring AI Alibaba plugin(such as larkSuite doc plugin and so on),the user may use the chatClient Builder method to build an LLM request. However, when we use it, we need to input function name. Due to the hard coding for function name, the answer perhaps returns **No function callback found for function name**.
So, How should we solve it?

**Comment by PolarishT** [comment]
solution: use APT(Annotaion Processing Tool) to build a static mapping (such as  chatClient.buillder().withfunctions(FunctionCalling.LarkSuite.createDoc).build()🟰 chatClient.buillder().withfunctions("LarkSuiteCreateDocFunction").build())

users only use mvn package can build this APT Class.

```java
processor.FunctionCalling.enable=true
processor.allFunctionCallingInstance.package=com.alibaba.cloud.ai.plugin
processor.allFunctionCallingInstance.className=your-class-name
```

**Comment by PolarishT** [comment]
cc @chickenlj I want to make an attempt to solve this issue.

**Comment by wstever** [comment]
seem good solution  to me

**Comment by qiqi5526** [comment]
Could you list a detail fix process @PolarishT

**Comment by PolarishT** [comment]
emm, this way to solve maybe not good way, I will give a new way to solve it. And I will paste the report to #198.

**Comment by Cirilla-zmh** [comment]
@PolarishT 
Hey, I have noticed your PR #217 and thanks for your attempts. It actually seems to be a parsing bug of `DashScopeAiStreamFunctionCallingHelper` while merging two contiguous complement messages. I have fixed this issue based on your PR and hope it could work well. (I could work as expected on my machine now)

I would close this issue and if you have any further questions, feel free to reopen it. ;)
