### ISSUE TITLE
Calling Function always throws Exception:No function callback found for function name

### ISSUE THREAD

**Issue by Mrs-Snow** [alibaba/spring-ai-alibaba#199]
Spring-ai-alibaba
Calling Function always throws Exception:No function callback found for function name, because the function name's value is always "" which I found by debug the code of DashScopeChatModel.

I need the progress do not throw the exception instead of telling user other info or abandon calling function.
I also want to known how can I prevent from this exception?

**Comment by Mrs-Snow** [comment]
and I also found,when the function has param 'chatId', the param's value will be modified to 1234567890

**Comment by hongshuo-wang** [comment]
I encountered the same exception while using the stream() function; however, the problem does not occur when I use call().

**Comment by Mrs-Snow** [comment]
> I encountered the same exception while using the stream() function; however, the problem does not occur when I use call().

Modify the class DashScopeAiStreamFunctionCallingHelper(line142) to 'String name = (current.name() != null && current.name().length() > 0 ? current.name() : previous.name());' The problem was fixed!

**Comment by Mrs-Snow** [comment]
> I encountered the same exception while using the stream() function; however, the problem does not occur when I use call().

using call will avoid method merge，so it does not occur。
