### ISSUE TITLE
mvn install error RELEASE does not allow version

### ISSUE THREAD

**Issue by suke1-tal** [alibaba/spring-ai-alibaba#20]
**Which Component**
./mvnw clean install -Pproduction  have a error

**Describe the bug**
[ERROR] Failed to execute goal on project playground-flight-booking: Could not collect dependencies for project com.alibaba.cloud.ai:playground-flight-booking:jar:0.0.1-SNAPSHOT
[ERROR] Failed to read artifact descriptor for com.alibaba.cloud.ai:spring-ai-alibaba-starter:jar:0.0.1-SNAPSHOT
[ERROR]         Caused by: The following artifacts could not be resolved: com.alibaba.cloud.ai:spring-ai-alibaba-starter:pom:0.0.1-SNAPSHOT (absent): Could not transfer artifact com.alibaba.cloud.ai:spring-ai-alibaba-starter:pom:0.0.1-SNAPSHOT from/to maven-central : status code: 400, reason phrase: Repository version policy: RELEASE does not allow version: 0.0.1-SNAPSHOT (400)

**Simplest demo**

**To Reproduce**
./mvnw clean install -Pproduction

**Comment by yuluo-yx** [comment]
你可以直接运行 application 启动类

**Comment by chickenlj** [comment]
> spring-ai-alibaba-starter:jar:0.0.1-SNAPSHOT

Pull the latest example code and try again, the latest release is `1.0.0-M2`
