### ISSUE TITLE
why can not use wanx-v1?

### ISSUE THREAD

**Issue by coderpwh1024** [alibaba/spring-ai-alibaba#29]
<img width="1696" alt="image" src="https://github.com/user-attachments/assets/ad30958b-bd1e-4a48-9f45-f859697f6322">
![image](https://github.com/user-attachments/assets/420d9aff-406a-4263-9110-dc72edcb6890)
![image](https://github.com/user-attachments/assets/e59009aa-c62d-4ada-add4-b7e115776546)

已经开通了wanx-v1，能在百炼大模型后台(阿里云)上使用，api-key 等均正确。message 提示不能异步调用等

**Comment by HeWeiGitHub** [comment]
我也遇到这个问题了，应该是底层还没有适配，直接调用dashscopeSDK

**Comment by JunJieLiu51520** [comment]
yes, i found the reason, please see  pr  #36 

@chickenlj  PTAL

**Comment by JunJieLiu51520** [comment]
@alibaba-oss @flystar32  PTAL

**Comment by kevinlin09** [comment]
fixed in commit: https://github.com/alibaba/spring-ai-alibaba/commit/1d59f0f6e30d743ac8790b5a0b824052b38c9398
