### ISSUE TITLE
The content returned by the stream() method contains a significant amount of repetition

### ISSUE THREAD

**Issue by HeWeiGitHub** [alibaba/spring-ai-alibaba#31]
The content returned by the stream() method contains a significant amount of repetition。
使用chatClient.prompt(prompt).stream().content();返回时存在大量重复内容。
代码如下：
![image](https://github.com/user-attachments/assets/d5568375-8a54-4796-a4e6-2d5ba07c92df)
![image](https://github.com/user-attachments/assets/6a6e1798-7b64-4958-be15-6b50d1c2fdf5)
![image](https://github.com/user-attachments/assets/f111fdbf-a528-4976-88fa-a4aa6c62f74a)
返回结果如下：
![image](https://github.com/user-attachments/assets/73709500-5121-48a1-8d04-b2f876662a3a)

软件版本：
Windows11、Java21 、 Version 1.0.0-M2

**Comment by loafer** [comment]
试下 String result = chatClient.prompt(prompt).call().content();

**Comment by kevinlin09** [comment]
@HeWeiGitHub 麻烦再测试下。在如下commit中已修复：https://github.com/alibaba/spring-ai-alibaba/commit/1fa218214f07baaeacb60c20a76e49437f066b66

**Comment by kevinlin09** [comment]
经过自测和其他开发者验证，流式增量输出问题已修复。可以下载最新源码，或等后续Release。
