### ISSUE TITLE
[RAG] Introduce reranking to the RAG retrieval process

### ISSUE THREAD

**Issue by chickenlj** [alibaba/spring-ai-alibaba#47]
* Introduce reranking step to retrieval process
* Add RAG example with reranking enabled

Frequently, not all results retrieved by RetrievalAdvisor are truly relevant to the user query. This is because, during the initial retrieval stage, it is often preferable to use faster and more cost-effective models, particularly when dealing with a large volume of data. The trade-off is that the retrieval quality may be lower.

Providing irrelevant information to the LLM can be costly and, in the worst case, lead to hallucinations. Therefore, in the second stage, we can perform re-ranking of the results obtained in the first stage and eliminate irrelevant results using a more advanced model (e.g., Cohere Rerank).

**Comment by robinyeeh** [comment]
done and close this issue.

**Comment by robinyeeh** [comment]
#54
