### ISSUE TITLE
[Example] add `spring-ai-alibaba` call others llms example

### ISSUE THREAD

**Issue by yuluo-yx** [alibaba/spring-ai-alibaba#56]

**Comment by wudihaoke214** [comment]
#59

**Comment by wudihaoke214** [comment]
[https://github.com/alibaba/spring-ai-alibaba/pull/59](url)

**Comment by wudihaoke214** [comment]
Help users quickly use spring ai alibaba to call other large models, including locally deployed ones such as ollama 
#59

**Comment by wblu214** [comment]
This issue has been resolved in this pull request    #59
